services:
  platform:
    image: ghcr.io/amroalshaban-afk/platform:0.1.0
    container_name: platform
    ports:
      - "8000"
  
  platform-operations-db:
    image: postgres:17
    container_name: platform-operations-db
    environment:
      POSTGRES_USER: ${PLATFORM_OPERATIONS_DB_USER}
      POSTGRES_PASSWORD: ${PLATFORM_OPERATIONS_DB_PASSWORD}
      POSTGRES_DB: ${PLATFORM_OPERATIONS_DB_NAME}
    volumes:
      - platform-operations-db-volume:/var/lib/postgresql/data
    env_file:
      - ".prod.env"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PLATFORM_OPERATIONS_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  caddy:
    image: caddy:2
    container_name: caddy
    depends_on:
      - platform
      - platform-operations-db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  platform-operations-db-volume:
  caddy_data:
  caddy_config: